const $ = (s) => document.querySelector(s);
const STORAGE = "voice-studio-project-v1";
const initialRows = [
  { text: "欢迎来到声工坊，开始制作你的声音作品。", override: true, voice: "female-shaonv", speed: 1.15, pitch: 2, volume: 0.92 },
  { text: "现在，你可以将一段文字变成富有表现力的声音。" },
  { text: "从导入脚本开始，逐行调整最适合的音色和节奏。", override: true, voice: "male-qn-qingse", speed: 0.9, pitch: 0, volume: 1 },
  { text: "每一条声音，都可以先单独试听。" },
  { text: "确认无误后，再将完整项目批量输出。" },
  { text: "让每一句话，都有恰到好处的温度。" }
];
const defaults = { apiBase: "https://voice-studio.faradaycrazy.workers.dev", model: "speech-2.8-hd", voice: "female-shaonv", speed: 1, pitch: 0, volume: 1, format: "mp3" };
const state = load();
const e = { body: $("#scriptBody"), text: $("#selectedText"), override: $("#overrideEnabled"), controls: $("#overrideControls"), audio: $("#audioPreview"), toast: $("#toast") };
const logs = [];

function load() { try { const saved = JSON.parse(localStorage.getItem(STORAGE)); if (saved?.rows?.length) return { ...saved, settings: { ...defaults, ...saved.settings, apiBase: saved.settings?.apiBase || defaults.apiBase }, selected: Math.min(saved.selected || 0, saved.rows.length - 1), selectedIds: saved.selectedIds || [0] }; } catch {} return { rows: initialRows.map((row, i) => ({ id: `${Date.now()}-${i}`, status: "待生成", ...row })), settings: { ...defaults }, selected: 0, selectedIds: [0] }; }
function persist() { const exportable = { ...state, rows: state.rows.map(({ audioUrl, ...row }) => row) }; localStorage.setItem(STORAGE, JSON.stringify(exportable)); $("#saveHint").textContent = "已保存"; }
function current() { return state.rows[state.selected]; }
function params(row) { return row.override ? { voice: row.voice || state.settings.voice, speed: +row.speed, pitch: +row.pitch, volume: +row.volume } : state.settings; }
function duration(row) { return row.duration || Math.max(1, Math.ceil((row.text || "").length / 5.2 / params(row).speed)); }
function time(seconds) { seconds = Math.max(0, Math.round(seconds)); return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }
function escape(value) { return String(value || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[c]); }
function toast(message, error = false) { e.toast.textContent = message; e.toast.classList.toggle("is-error", error); e.toast.classList.add("is-visible"); clearTimeout(toast.timer); toast.timer = setTimeout(() => e.toast.classList.remove("is-visible"), 3800); }
function log(message, level = "INFO") { const stamp = new Date().toLocaleTimeString("zh-CN", { hour12: false }); logs.unshift(`[${stamp}] ${level.padEnd(5)} ${message}`); logs.splice(80); const output = $("#logOutput"); if (output) output.textContent = logs.join("\n"); }
function valueLabel(input, kind) { const out = $(`#${input.id}Output`); if (!out) return; const value = +input.value; out.textContent = kind === "speed" ? `${value.toFixed(2).replace(/0$/, "")}×` : kind === "volume" ? `${Math.round(value * 100)}%` : `${value > 0 ? "+" : ""}${value}`; }
function renderGlobals() { const s = state.settings; $("#apiBaseUrl").value = s.apiBase; $("#globalModel").value = s.model; $("#globalVoice").value = s.voice; [["globalSpeed", "speed"], ["globalPitch", "pitch"], ["globalVolume", "volume"]].forEach(([id, kind]) => { const input = $(`#${id}`); input.value = s[kind]; valueLabel(input, kind); }); document.querySelectorAll(".format-chip").forEach((b) => b.classList.toggle("active", b.dataset.format === s.format)); $("#formatSummary").textContent = s.format.toUpperCase(); }
function renderRows() { e.body.replaceChildren(...state.rows.map((row, index) => { const voice = params(row).voice; const tr = document.createElement("tr"); if (index === state.selected) tr.classList.add("is-selected"); const status = row.status || "待生成"; tr.innerHTML = `<td><input class="row-check" data-index="${index}" type="checkbox" ${state.selectedIds.includes(index) ? "checked" : ""} aria-label="选择第 ${index + 1} 条" /></td><td>${String(index + 1).padStart(2, "0")}</td><td class="script-text"><strong>${escape(row.text || "未填写文本")}</strong><span>${(row.text || "").length} 个字符</span></td><td><span class="mini-avatar ${voice.includes("male") ? "coral" : ""}">${voice.includes("male") ? "男" : "声"}</span>${escape(voice)}</td><td><span class="${row.override ? "override-tag" : "inherit-tag"}">${row.override ? "已单独设置" : "使用全局"}</span></td><td>${time(duration(row))}</td><td><span class="status ${status === "已生成" ? "status-ready" : "status-pending"}"><i></i>${status}</span></td><td><button class="row-more" data-index="${index}" data-download="${row.audioUrl ? "yes" : "no"}" title="${row.audioUrl ? "下载音频" : "编辑"}">${row.audioUrl ? "↓" : "•••"}</button></td>`; tr.addEventListener("click", (event) => { if (!event.target.matches("input,button")) select(index); }); return tr; })); }
function renderInspector() { const row = current(); if (!row) return; $("#selectedRowLabel").textContent = `ROW ${String(state.selected + 1).padStart(2, "0")}`; e.text.value = row.text || ""; e.override.checked = !!row.override; e.controls.hidden = !row.override; const p = params(row); $("#rowVoice").value = p.voice; [["rowSpeed", "speed"], ["rowPitch", "pitch"], ["rowVolume", "volume"]].forEach(([id, kind]) => { const input = $(`#${id}`); input.value = p[kind]; valueLabel(input, kind); }); $("#rowEstimate").textContent = `预计 ${time(duration(row))}`; e.audio.hidden = !row.audioUrl; e.audio.src = row.audioUrl || ""; }
function renderStats() { const total = state.rows.length; const generated = state.rows.filter((r) => r.status === "已生成").length; $("#totalCount").textContent = String(total).padStart(2, "0"); $("#rowCountChip").textContent = `${total} 条`; $("#generateCount").textContent = `${total} 条`; $("#completedCount").innerHTML = `${String(generated).padStart(2, "0")} <small>/ ${String(total).padStart(2, "0")}</small>`; $("#estimatedDuration").textContent = time(state.rows.reduce((sum, r) => sum + duration(r), 0)); $("#selectedCount").textContent = state.selectedIds.length; $("#selectAll").checked = total > 0 && state.selectedIds.length === total; }
function render() { renderGlobals(); renderRows(); renderInspector(); renderStats(); persist(); }
function select(index) { state.selected = index; if (!state.selectedIds.includes(index)) state.selectedIds.push(index); render(); }
function add(text = "") { state.rows.push({ id: `${Date.now()}-${state.rows.length}`, text, status: "待生成" }); state.selected = state.rows.length - 1; state.selectedIds = [state.selected]; render(); log(`新增第 ${state.rows.length} 条文本。`); e.text.focus(); }
function apiBase() { return state.settings.apiBase.replace(/\/$/, ""); }
function hexBlob(hex, format) { const bytes = new Uint8Array(hex.length / 2); for (let i = 0; i < bytes.length; i += 1) bytes[i / 2] = parseInt(hex.slice(i, i + 2), 16); return new Blob([bytes], { type: `audio/${format}` }); }
async function generate(index) { const row = state.rows[index]; if (!row?.text?.trim()) throw new Error("文本不能为空"); if (!apiBase()) throw new Error("请先填写语音接口地址"); row.status = "生成中"; render(); const p = params(row); log(`第 ${index + 1} 条开始生成：模型 ${state.settings.model}，音色 ${p.voice}。`); const response = await fetch(`${apiBase()}/api/tts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ model: state.settings.model, text: row.text.trim(), stream: false, voice_setting: { voice_id: p.voice, speed: p.speed, vol: p.volume, pitch: p.pitch }, audio_setting: { sample_rate: 32000, bitrate: 128000, format: state.settings.format, channel: 1 }, output_format: "hex", subtitle_enable: false }) }); const body = await response.json().catch(() => ({})); if (!response.ok || body.base_resp?.status_code) throw new Error(body.base_resp?.status_msg || body.error || "MiniMax 请求失败"); if (!body.data?.audio) throw new Error("接口未返回音频数据"); if (row.audioUrl) URL.revokeObjectURL(row.audioUrl); row.audioUrl = URL.createObjectURL(hexBlob(body.data.audio, state.settings.format)); row.duration = Math.round((body.extra_info?.audio_length || duration(row) * 1000) / 1000); row.status = "已生成"; render(); log(`第 ${index + 1} 条生成成功：${time(row.duration)}，追踪 ID ${body.trace_id || "未提供"}。`, "OK"); return row; }
async function generateMany(indices) { const list = [...new Set(indices)].filter((index) => state.rows[index]); if (!list.length) return toast("请先选择一条文本", true); log(`开始处理 ${list.length} 条配音任务。`); let count = 0; for (const index of list) { try { await generate(index); count += 1; } catch (error) { state.rows[index].status = "失败"; render(); log(`第 ${index + 1} 条生成失败：${error.message}`, "ERROR"); toast(`第 ${index + 1} 条失败：${error.message}`, true); } } if (count) { log(`任务完成：成功 ${count}/${list.length} 条。`, "OK"); toast(`已生成 ${count} 条音频`); } }
function download(index) { const row = state.rows[index]; if (!row?.audioUrl) return; const link = document.createElement("a"); link.href = row.audioUrl; link.download = `voice-${String(index + 1).padStart(2, "0")}.${state.settings.format}`; link.click(); log(`已下载第 ${index + 1} 条音频。`, "OK"); }
function importFile(file) { const reader = new FileReader(); reader.onload = () => { try { const wb = XLSX.read(reader.result, { type: "array" }); const data = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1, defval: "" }); const start = data[0]?.some((v) => /文本|text/i.test(String(v))) ? 1 : 0; const rows = data.slice(start).map((line) => String(line[0] || "").trim()).filter(Boolean); if (!rows.length) throw new Error("未找到第一列文本"); state.rows = rows.map((text, i) => ({ id: `${Date.now()}-${i}`, text, status: "待生成" })); state.selected = 0; state.selectedIds = [0]; render(); log(`已从 ${file.name} 导入 ${rows.length} 条文本。`, "OK"); toast(`已导入 ${rows.length} 条文本`); } catch (error) { log(`导入失败：${error.message}`, "ERROR"); toast(`导入失败：${error.message}`, true); } }; reader.readAsArrayBuffer(file); }
function exportExcel() { const data = [["文本", "音色 ID", "语速", "音调", "音量", "状态"]].concat(state.rows.map((row) => { const p = params(row); return [row.text, p.voice, p.speed, p.pitch, p.volume, row.status]; })); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(data), "配音文本"); XLSX.writeFile(wb, "voice-studio.xlsx"); }
function exportProject() { const body = JSON.stringify({ ...state, rows: state.rows.map(({ audioUrl, ...row }) => row) }, null, 2); const url = URL.createObjectURL(new Blob([body], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "voice-studio-project.json"; link.click(); URL.revokeObjectURL(url); }
function bind() {
  $("#addTextBtn").onclick = () => add(); $("#addRowBtn").onclick = () => add(); $("#excelInput").onchange = (event) => event.target.files[0] && importFile(event.target.files[0]); $("#exportExcelBtn").onclick = () => { exportExcel(); log("已导出 Excel 文本表。", "OK"); }; $("#exportProjectBtn").onclick = () => { exportProject(); log("已导出项目配置。", "OK"); }; $("#testRowBtn").onclick = () => generateMany([state.selected]); $("#generateAllBtn").onclick = () => generateMany(state.rows.map((_, i) => i)); $("#clearSelectionBtn").onclick = () => { state.selectedIds = []; render(); log("已取消所有文本选择。"); }; $("#deleteRowBtn").onclick = () => { if (state.rows.length < 2) return toast("至少保留一条文本", true); state.rows.splice(state.selected, 1); state.selected = Math.max(0, state.selected - 1); state.selectedIds = [state.selected]; render(); log("已删除当前文本。"); }; $("#clearAudioBtn").onclick = () => { state.rows.forEach((r) => { if (r.audioUrl) URL.revokeObjectURL(r.audioUrl); delete r.audioUrl; delete r.duration; r.status = "待生成"; }); render(); log("已清除全部音频结果。"); toast("已清除音频结果"); }; $("#apiHelpBtn").onclick = () => toast("MiniMax Key 只保存在接口服务器的 MINIMAX_API_KEY 环境变量中。") ; $("#resetProjectBtn").onclick = () => { localStorage.removeItem(STORAGE); location.reload(); }; $("#clearLogBtn").onclick = () => { logs.length = 0; $("#logOutput").textContent = "日志已清空。"; }; $("#toggleLogBtn").onclick = () => { const panel = $("#logPanel"); const collapsed = panel.classList.toggle("is-collapsed"); $("#toggleLogBtn").setAttribute("aria-expanded", String(!collapsed)); $("#logToggleText").textContent = collapsed ? "展开日志" : "收起日志"; };
  e.body.onchange = (event) => { if (!event.target.matches(".row-check")) return; const index = +event.target.dataset.index; state.selectedIds = event.target.checked ? [...new Set([...state.selectedIds, index])] : state.selectedIds.filter((i) => i !== index); state.selected = index; render(); }; e.body.onclick = (event) => { const button = event.target.closest("button[data-index]"); if (!button) return; const index = +button.dataset.index; button.dataset.download === "yes" ? download(index) : select(index); }; $("#selectAll").onchange = (event) => { state.selectedIds = event.target.checked ? state.rows.map((_, i) => i) : []; render(); };
  e.text.oninput = () => { current().text = e.text.value; render(); }; e.override.onchange = () => { const row = current(); row.override = e.override.checked; if (row.override) Object.assign(row, params(row)); render(); }; [["rowVoice", "voice"], ["rowSpeed", "speed"], ["rowPitch", "pitch"], ["rowVolume", "volume"]].forEach(([id, kind]) => { $(`#${id}`).oninput = (event) => { const row = current(); row.override = true; row[kind] = kind === "voice" ? event.target.value.trim() : +event.target.value; if (kind !== "voice") valueLabel(event.target, kind); render(); }; }); $("#resetRowBtn").onclick = () => { current().override = false; render(); };
  [["apiBaseUrl", "apiBase"], ["globalModel", "model"], ["globalVoice", "voice"], ["globalSpeed", "speed"], ["globalPitch", "pitch"], ["globalVolume", "volume"]].forEach(([id, kind]) => { $(`#${id}`).oninput = (event) => { state.settings[kind] = ["apiBase", "model", "voice"].includes(kind) ? event.target.value.trim() : +event.target.value; if (!["apiBase", "model", "voice"].includes(kind)) valueLabel(event.target, kind); render(); }; }); document.querySelectorAll(".format-chip").forEach((button) => button.onclick = () => { state.settings.format = button.dataset.format; render(); });
}
bind(); render(); log("工作台已就绪，等待配音任务。");
