const $ = (s) => document.querySelector(s);
const STORAGE = "voice-studio-project-v1";
const SAVED_AT_STORAGE = "voice-studio-project-saved-at-v1";
const LOCAL_ASSISTANT_URL = "http://127.0.0.1:8789";
const initialRows = [
  { text: "欢迎来到 JP-merge！合成相同物品，解锁更多惊喜。", override: true, voice: "female-shaonv", speed: 1.15, pitch: 2, volume: 0.92 },
  { text: "拖动两个相同的物品合并，获得更高级的奖励。" },
  { text: "完成订单，收集金币，打造属于你的温馨小镇。", override: true, voice: "male-qn-qingse", speed: 0.9, pitch: 0, volume: 1 },
  { text: "新的任务已经到达，快来看看需要哪些物品吧。" },
  { text: "恭喜你解锁了新的区域，更多故事正在等待开启。" },
  { text: "每天登录领取奖励，让你的合成之旅更加轻松。" }
];
const defaults = { apiBase: "https://voice-studio.faradaycrazy.workers.dev", model: "speech-2.8-hd", voice: "female-shaonv", speed: 1, pitch: 0, volume: 1, format: "mp3", filenameCode: "" };
let restoredProject = false;
let lastSavedAt = 0;
const state = load();
const e = { body: $("#scriptBody"), text: $("#selectedText"), override: $("#overrideEnabled"), controls: $("#overrideControls"), audio: $("#audioPreview"), toast: $("#toast") };
const logs = [];
const AUTH_STORAGE = "voice-studio-session-auth";
const AUTH_NAME_STORAGE = "voice-studio-session-name";
let voiceCatalog = [];
let voiceDialogSelection = new Set();
let dingTalkWorkbookId = "";
let dingTalkRecords = [];
let dingTalkHeaders = [];
let googleSpreadsheetId = "";
let googleRecords = [];
let googleHeaders = [];
let googleWriteSpreadsheetId = "";
let googleActivityEntries = [];

const legacyDemoSequences = [["欢迎来到声工坊，开始制作你的声音作品。", "现在，你可以将一段文字变成富有表现力的声音。", "从导入脚本开始，逐行调整最适合的音色和节奏。", "每一条声音，都可以先单独试听。", "确认无误后，再将完整项目批量输出。", "让每一句话，都有恰到好处的温度。"], ["欢迎使用 JP-merge 配音工具，开始制作你的声音作品。", "现在，你可以将一段文字变成富有表现力的声音。", "从导入脚本开始，逐行调整最适合的音色和节奏。", "每一条声音，都可以先单独试听。", "确认无误后，再将完整项目批量输出。", "让每一句话，都有恰到好处的温度。"]];
function initialState() { return { rows: initialRows.map((row, i) => ({ id: `${Date.now()}-${i}`, status: "待生成", ...row })), settings: { ...defaults }, selected: 0, selectedIds: [0], voiceFilter: null, googleImport: { roleColumn: "", textColumn: "", keyColumn: "", characterNames: "" } }; }
function isLegacyDemo(rows) { return legacyDemoSequences.some((texts) => rows.length === texts.length && rows.every((row, index) => row.text === texts[index])); }
function load() { try { const saved = JSON.parse(localStorage.getItem(STORAGE)); if (saved?.rows?.length) { if (isLegacyDemo(saved.rows)) return initialState(); restoredProject = true; lastSavedAt = Number(localStorage.getItem(SAVED_AT_STORAGE)) || 0; const rows = saved.rows.map(({ audioUrl, duration, ...row }) => ({ ...row, status: row.status === "生成中" ? "待生成" : row.status || "待生成" })); return { ...saved, rows, settings: { ...defaults, ...saved.settings, apiBase: saved.settings?.apiBase || defaults.apiBase }, selected: Math.min(saved.selected || 0, rows.length - 1), selectedIds: (saved.selectedIds || [0]).filter((index) => index >= 0 && index < rows.length), voiceFilter: Array.isArray(saved.voiceFilter) ? saved.voiceFilter : null }; } } catch {} return initialState(); }
function savedTimeLabel(timestamp) { return new Date(timestamp).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit", hour12: false }); }
function updateSaveHint(restored = false) { const hint = $("#saveHint"); if (!hint) return; hint.textContent = lastSavedAt ? `${restored ? "已恢复" : "自动保存"} · ${savedTimeLabel(lastSavedAt)}` : restored ? "已恢复上次保存" : "本地保存"; }
function saveProject(manual = false) { try { const exportable = { ...state, rows: state.rows.map(({ audioUrl, duration, ...row }) => row) }; localStorage.setItem(STORAGE, JSON.stringify(exportable)); lastSavedAt = Date.now(); localStorage.setItem(SAVED_AT_STORAGE, String(lastSavedAt)); updateSaveHint(); if (manual) { toast("正在保存项目…"); log("正在保存项目。", "INFO"); saveDesktopProject(exportable); } return true; } catch (error) { $("#saveHint").textContent = "保存失败"; if (manual) toast("保存失败，请检查浏览器存储空间", true); log(`项目保存失败：${error.message}`, "ERROR"); return false; } }
function persist() { return saveProject(false); }
async function saveDesktopProject(project) { try { const result = await localAssistant("/project/save", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ project }) }); toast("项目已保存到桌面应用"); log(`项目已保存：${result.path}`, "OK"); } catch (error) { toast("项目已保存到当前浏览器；桌面文件未写入", true); log(`桌面项目文件保存失败：${error.message}`, "ERROR"); } }
async function restoreDesktopProject() { try { const result = await localAssistant("/project/load"); const project = result.project; if (!result.exists || !project || !Array.isArray(project.rows) || !project.rows.length) return; state.rows = project.rows.map(({ audioUrl, duration, ...row }) => ({ ...row, status: row.status === "生成中" ? "待生成" : row.status || "待生成" })); state.settings = { ...defaults, ...project.settings, apiBase: project.settings?.apiBase || defaults.apiBase }; state.selected = Math.min(project.selected || 0, state.rows.length - 1); state.selectedIds = (project.selectedIds || [state.selected]).filter((index) => index >= 0 && index < state.rows.length); state.voiceFilter = Array.isArray(project.voiceFilter) ? project.voiceFilter : null; state.googleImport = project.googleImport || state.googleImport; restoredProject = true; render(false); saveProject(false); log("已从桌面项目文件恢复上次保存的内容。", "OK"); } catch (error) { log(`未读取桌面项目文件：${error.message}`, "INFO"); } }
window.addEventListener("load", () => { restoreDesktopProject(); });
function current() { return state.rows[state.selected]; }
function params(row) { return row.override ? { voice: row.voice || state.settings.voice, speed: +row.speed, pitch: +row.pitch, volume: +row.volume } : state.settings; }
function duration(row) { return row.duration || Math.max(1, Math.ceil((row.text || "").length / 5.2 / params(row).speed)); }
function time(seconds) { seconds = Math.max(0, Math.round(seconds)); return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }
function escape(value) { return String(value || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[c]); }
function toast(message, error = false) { e.toast.textContent = message; e.toast.classList.toggle("is-error", error); e.toast.classList.add("is-visible"); clearTimeout(toast.timer); toast.timer = setTimeout(() => e.toast.classList.remove("is-visible"), 3800); }
function log(message, level = "INFO") { const stamp = new Date().toLocaleTimeString("zh-CN", { hour12: false }); logs.unshift(`[${stamp}] ${level.padEnd(5)} ${message}`); logs.splice(80); const output = $("#logOutput"); if (output) output.textContent = logs.join("\n"); }
function valueLabel(input, kind) { const out = $(`#${input.id}Output`); if (!out) return; const value = +input.value; out.textContent = kind === "speed" ? `${value.toFixed(2).replace(/0$/, "")}×` : kind === "volume" ? `${Math.round(value * 100)}%` : `${value > 0 ? "+" : ""}${value}`; }
function renderGlobals() { const s = state.settings; $("#apiBaseUrl").value = s.apiBase; $("#globalModel").value = s.model; $("#filenameCode").value = s.filenameCode || ""; $("#filenameRuleHint").textContent = `导入带 Key 的文本后，文件名示例：C${s.filenameCode || "X"}_01_001.${s.format}`; [["globalSpeed", "speed"], ["globalPitch", "pitch"], ["globalVolume", "volume"]].forEach(([id, kind]) => { const input = $(`#${id}`); input.value = s[kind]; valueLabel(input, kind); }); document.querySelectorAll(".format-chip").forEach((b) => b.classList.toggle("active", b.dataset.format === s.format)); $("#formatSummary").textContent = s.format.toUpperCase(); }
function renderRows() { e.body.replaceChildren(...state.rows.map((row, index) => { const voice = params(row).voice; const tr = document.createElement("tr"); if (index === state.selected) tr.classList.add("is-selected"); const status = row.status || "待生成"; tr.innerHTML = `<td><input class="row-check" data-index="${index}" type="checkbox" ${state.selectedIds.includes(index) ? "checked" : ""} aria-label="选择第 ${index + 1} 条" /></td><td>${String(index + 1).padStart(2, "0")}</td><td class="script-text"><strong>${escape(row.text || "未填写文本")}</strong><span>${(row.text || "").length} 个字符</span></td><td><span class="mini-avatar ${voice.includes("male") ? "coral" : ""}">${voice.includes("male") ? "男" : "声"}</span>${escape(voice)}</td><td><span class="${row.override ? "override-tag" : "inherit-tag"}">${row.override ? "已单独设置" : "使用全局"}</span></td><td>${time(duration(row))}</td><td><span class="status ${status === "已生成" ? "status-ready" : "status-pending"}"><i></i>${status}</span></td><td><button class="row-more" data-index="${index}" data-download="${row.audioUrl ? "yes" : "no"}" title="${row.audioUrl ? "下载音频" : "编辑"}">${row.audioUrl ? "↓" : "•••"}</button></td>`; tr.addEventListener("click", (event) => { if (!event.target.matches("input,button")) select(index); }); return tr; })); }
function renderInspector() { const row = current(); if (!row) return; $("#selectedRowLabel").textContent = `ROW ${String(state.selected + 1).padStart(2, "0")}`; e.text.value = row.text || ""; e.override.checked = !!row.override; e.controls.hidden = !row.override; const p = params(row); [["rowSpeed", "speed"], ["rowPitch", "pitch"], ["rowVolume", "volume"]].forEach(([id, kind]) => { const input = $(`#${id}`); input.value = p[kind]; valueLabel(input, kind); }); $("#rowEstimate").textContent = `预计 ${time(duration(row))}`; e.audio.hidden = !row.audioUrl; e.audio.src = row.audioUrl || ""; }
function renderStats() { const total = state.rows.length; const generated = state.rows.filter((r) => r.status === "已生成").length; $("#totalCount").textContent = String(total).padStart(2, "0"); $("#rowCountChip").textContent = `${total} 条`; $("#generateCount").textContent = `${total} 条`; $("#completedCount").innerHTML = `${String(generated).padStart(2, "0")} <small>/ ${String(total).padStart(2, "0")}</small>`; $("#estimatedDuration").textContent = time(state.rows.reduce((sum, r) => sum + duration(r), 0)); $("#selectedCount").textContent = state.selectedIds.length; $("#selectAll").checked = total > 0 && state.selectedIds.length === total; }
function render(save = true) { renderGlobals(); renderRows(); renderInspector(); renderVoiceOptions(); renderStats(); if (save) persist(); }
function select(index) { state.selected = index; if (!state.selectedIds.includes(index)) state.selectedIds.push(index); render(); }
function add(text = "") { state.rows.push({ id: `${Date.now()}-${state.rows.length}`, text, status: "待生成" }); state.selected = state.rows.length - 1; state.selectedIds = [state.selected]; render(); log(`新增第 ${state.rows.length} 条文本。`); e.text.focus(); }
function replaceImportedRows(rows, source) { state.rows.forEach((row) => { if (row.audioUrl) URL.revokeObjectURL(row.audioUrl); }); state.rows = rows; state.selected = 0; state.selectedIds = rows.length ? [0] : []; render(); log(`已用 ${source} 替换当前文本；此前文本和已生成音频已清空。`, "OK"); }
function apiBase() { return state.settings.apiBase.replace(/\/$/, ""); }
function authToken(username, password) { const bytes = new TextEncoder().encode(`${username}:${password}`); return `Basic ${btoa(String.fromCharCode(...bytes))}`; }
function savedAuth() { return sessionStorage.getItem(AUTH_STORAGE) || ""; }
function voiceEntries(body) { const groups = [{ key: "system_voice", label: "系统音色" }, { key: "voice_cloning", label: "我的复刻音色" }, { key: "voice_generation", label: "我的设计音色" }]; return groups.flatMap(({ key, label }) => (body?.[key] || []).map((voice) => ({ id: String(voice.voice_id || "").trim(), name: String(voice.voice_name || "").trim(), description: Array.isArray(voice.description) ? voice.description.filter(Boolean).join("；") : "", group: label })).filter((voice) => voice.id)); }
function visibleVoices() { return state.voiceFilter === null ? voiceCatalog : voiceCatalog.filter((voice) => state.voiceFilter.includes(voice.id)); }
function setVoiceOptions(select, value) { const selected = String(value || "").trim() || defaults.voice; const available = visibleVoices(); const entries = available.some((voice) => voice.id === selected) ? available : [{ id: selected, name: "当前音色", description: "", group: "当前选择" }, ...available]; const groups = new Map(); entries.forEach((voice) => groups.set(voice.group, [...(groups.get(voice.group) || []), voice])); select.replaceChildren(...[...groups].map(([label, voices]) => { const group = document.createElement("optgroup"); group.label = label; voices.forEach((voice) => { const option = document.createElement("option"); option.value = voice.id; option.textContent = `${voice.name || voice.id} · ${voice.id}`; if (voice.description) option.title = voice.description; group.append(option); }); return group; })); select.value = selected; }
function renderVoiceOptions() { setVoiceOptions($("#globalVoice"), state.settings.voice); setVoiceOptions($("#rowVoice"), params(current()).voice); }
async function loadVoices() { if (!savedAuth()) return; const hint = $("#voiceCatalogHint"); hint.textContent = "正在加载可用音色…"; const response = await fetch(`${apiBase()}/api/voices`, { headers: { "X-Voice-Studio-Auth": savedAuth() } }); const body = await response.json().catch(() => ({})); if (response.status === 401) { logout("登录已失效，请重新登录"); throw new Error("登录已失效"); } if (!response.ok || body.base_resp?.status_code) throw new Error(body.base_resp?.status_msg || body.error || "音色列表加载失败"); voiceCatalog = voiceEntries(body); renderVoiceOptions(); const visible = visibleVoices().length; hint.textContent = state.voiceFilter === null ? `已加载全部 ${voiceCatalog.length} 个音色` : `下拉菜单显示 ${visible} / ${voiceCatalog.length} 个音色`; log(`已加载 ${voiceCatalog.length} 个可用音色。`, "OK"); }
function renderVoiceDialog() { const query = $("#voiceSearch").value.trim().toLowerCase(); const voices = voiceCatalog.filter((voice) => !query || `${voice.name} ${voice.id} ${voice.description}`.toLowerCase().includes(query)); $("#voiceSelectionSummary").textContent = `已选 ${voiceDialogSelection.size} / ${voiceCatalog.length} 个音色；当前显示 ${voices.length} 个结果`; const list = $("#voicePickerList"); list.replaceChildren(...(voices.length ? voices.map((voice) => { const label = document.createElement("label"); label.className = "voice-picker-item"; label.innerHTML = `<input type="checkbox" value="${escape(voice.id)}" ${voiceDialogSelection.has(voice.id) ? "checked" : ""} /><span><b>${escape(voice.name || voice.id)}</b><small>${escape(voice.id)}</small>${voice.description ? `<em>${escape(voice.description)}</em>` : ""}</span>`; return label; }) : [Object.assign(document.createElement("p"), { className: "voice-picker-empty", textContent: "没有匹配的音色" })])); }
async function openVoiceDialog() { if (!voiceCatalog.length) await loadVoices(); voiceDialogSelection = new Set(state.voiceFilter === null ? voiceCatalog.map((voice) => voice.id) : state.voiceFilter); $("#voiceSearch").value = ""; renderVoiceDialog(); $("#voiceDialog").hidden = false; $("#voiceSearch").focus(); }
function closeVoiceDialog() { $("#voiceDialog").hidden = true; }
function saveVoiceFilter() { state.voiceFilter = [...voiceDialogSelection]; render(); const visible = visibleVoices().length; $("#voiceCatalogHint").textContent = `下拉菜单显示 ${visible} / ${voiceCatalog.length} 个音色`; persist(); closeVoiceDialog(); toast(`已筛选 ${visible} 个下拉菜单音色`); log(`已筛选下拉菜单音色：${visible} 个。`, "OK"); }
async function localAssistant(path, options = {}) { const response = await fetch(`${LOCAL_ASSISTANT_URL}${path}`, options); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error([body.error || "本机文档助手请求失败", body.diagnostic].filter(Boolean).join("\n")); return body; }
function setDingTalkStatus(message, kind = "") { const status = $("#dingTalkStatus"); status.textContent = message; status.className = `assistant-status${kind ? ` is-${kind}` : ""}`; }
function closeDingTalkDialog() { $("#dingTalkDialog").hidden = true; }
async function openDingTalkDialog() { $("#dingTalkDialog").hidden = false; setDingTalkStatus("正在检测本机文档助手…"); try { const health = await localAssistant("/health"); setDingTalkStatus(`本机文档助手已连接 · ${health.operatorConfigured ? "操作人身份已配置" : "缺少操作人 unionId"}`, health.configured ? "ready" : "error"); if (!health.configured) throw new Error("请先在本机 .env 配置钉钉凭据和操作人 unionId"); } catch (error) { setDingTalkStatus("未连接本机助手。请运行 启动本机助手.cmd 后重试。", "error"); log(`本机文档助手不可用：${error.message}`, "ERROR"); } }
function dingTalkRequestBody(extra = {}) { return { workbook: dingTalkWorkbookId || $("#dingTalkUrl").value.trim(), sheet: $("#dingTalkSheet").value, headerRow: +$("#dingTalkHeaderRow").value, startRow: +$("#dingTalkStartRow").value, endRow: +$("#dingTalkEndRow").value, ...extra }; }
async function loadDingTalkSheets() { const workbook = $("#dingTalkUrl").value.trim(); if (!workbook) return toast("请先粘贴钉钉表格链接或 Workbook ID", true); const button = $("#loadDingTalkSheetsBtn"); button.disabled = true; button.textContent = "正在读取…"; try { const data = await localAssistant("/dingtalk/sheets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workbook }) }); dingTalkWorkbookId = data.workbookId; const sheet = $("#dingTalkSheet"); sheet.replaceChildren(...data.sheets.map((item) => Object.assign(document.createElement("option"), { value: item.name, textContent: item.name }))); sheet.disabled = false; $("#previewDingTalkBtn").disabled = !data.sheets.length; $("#dingTalkPreviewHint").textContent = `已读取 ${data.sheets.length} 个工作表`; dingTalkRecords = []; dingTalkHeaders = []; $("#dingTalkColumns").hidden = true; $("#dingTalkPreview").hidden = true; log(`已读取钉钉表格 ${data.workbookId} 的 ${data.sheets.length} 个工作表。`, "OK"); } catch (error) { toast(error.message, true); log(`读取钉钉工作表失败：${error.message}`, "ERROR"); } finally { button.disabled = false; button.textContent = "读取工作表"; } }
function selectedDingTalkHeaders() { return [...document.querySelectorAll("#dingTalkColumns input:checked")].map((input) => input.value); }
function renderDingTalkPreview() { const columns = $("#dingTalkColumns"); columns.replaceChildren(...dingTalkHeaders.map((header) => { const label = document.createElement("label"); label.className = "document-column"; label.innerHTML = `<input type="checkbox" value="${escape(header)}" checked /> ${escape(header)}`; return label; })); columns.hidden = !dingTalkHeaders.length; const preview = $("#dingTalkPreview"); const lines = dingTalkRecords.slice(0, 12).map((record) => dingTalkHeaders.map((header) => `${header}: ${record[header] || ""}`).join("  |  ")).filter(Boolean); preview.textContent = lines.length ? `${lines.join("\n")}\n\n共读取 ${dingTalkRecords.length} 行；勾选需要导入的列。` : "未读取到可导入的文本。"; preview.hidden = false; $("#importDingTalkTextBtn").disabled = !dingTalkRecords.length || !dingTalkHeaders.length; }
async function previewDingTalk() { if (!$("#dingTalkSheet").value) return toast("请先读取并选择工作表", true); const { headerRow, startRow, endRow } = dingTalkRequestBody(); if (!headerRow || !startRow || !endRow || endRow < startRow) return toast("请检查表头行与起止行", true); const button = $("#previewDingTalkBtn"); button.disabled = true; button.textContent = "正在读取…"; try { const data = await localAssistant("/dingtalk/read", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(dingTalkRequestBody()) }); dingTalkHeaders = data.headers || []; dingTalkRecords = data.records || []; renderDingTalkPreview(); $("#dingTalkPreviewHint").textContent = `已读取 ${dingTalkRecords.length} 行、${dingTalkHeaders.length} 列`; log(`已从钉钉文档读取 ${dingTalkRecords.length} 行文本预览。`, "OK"); } catch (error) { toast(error.message, true); log(`读取钉钉文档内容失败：${error.message}`, "ERROR"); } finally { button.disabled = false; button.textContent = "读取列与预览"; } }
function importDingTalkText() { const headers = selectedDingTalkHeaders(); if (!headers.length) return toast("请至少选择一列", true); const texts = dingTalkRecords.flatMap((record) => headers.map((header) => String(record[header] || "").trim()).filter(Boolean)); if (!texts.length) return toast("所选列没有可导入的文本", true); const rows = texts.map((text, index) => ({ id: `${Date.now()}-${index}`, text, status: "待生成" })); replaceImportedRows(rows, "钉钉文档"); closeDingTalkDialog(); toast(`已导入 ${rows.length} 条钉钉文本，并清空此前文本`); }
function setGoogleStatus(id, message, kind = "") { const status = $(`#${id}`); status.textContent = message; status.className = `assistant-status${kind ? ` is-${kind}` : ""}`; }
function googleActivity(message, level = "INFO") { const stamp = new Date().toLocaleTimeString("zh-CN", { hour12: false }); googleActivityEntries.unshift(`[${stamp}] ${level} ${message}`); googleActivityEntries.splice(0, 20); const output = $("#googleActivity"); if (output) output.textContent = googleActivityEntries.join("\n"); }
async function checkGoogleAssistant(statusId) { setGoogleStatus(statusId, "正在检测 Google 服务账号…"); try { const health = await localAssistant("/google/health"); if (!health.configured) throw new Error(health.error || "未找到服务账号凭据或 Google 认证组件"); setGoogleStatus(statusId, "Google 服务账号已就绪 · 将只访问已分享给该账号的表格", "ready"); googleActivity("服务账号已就绪。", "OK"); return true; } catch (error) { setGoogleStatus(statusId, error.message, "error"); googleActivity(`服务账号检查失败：${error.message}`, "ERROR"); return false; } }
function closeGoogleSheetDialog() { $("#googleSheetDialog").hidden = true; }
function googleImportBody(extra = {}) { return { spreadsheet: googleSpreadsheetId || $("#googleSheetUrl").value.trim(), sheet: $("#googleSheetTab").value, headerRow: +$("#googleHeaderRow").value, startRow: +$("#googleStartRow").value, endRow: +$("#googleEndRow").value, ...extra }; }
async function openGoogleSheetDialog() { $("#googleSheetDialog").hidden = false; googleActivityEntries = []; googleActivity("请粘贴 Google 表格链接，然后点击“1. 获取工作表”。"); await checkGoogleAssistant("googleSheetStatus"); }
async function loadGoogleImportSheets() { const spreadsheet = $("#googleSheetUrl").value.trim(); if (!spreadsheet) { setGoogleStatus("googleSheetStatus", "请先粘贴 Google 表格链接或 Spreadsheet ID", "error"); googleActivity("读取工作表失败：未填写 Google 表格链接。", "ERROR"); return; } const button = $("#loadGoogleSheetsBtn"); button.disabled = true; button.textContent = "正在读取…"; googleActivity("正在读取工作表列表…"); try { const data = await localAssistant("/google/sheets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ spreadsheet }) }); googleSpreadsheetId = data.spreadsheetId; const select = $("#googleSheetTab"); select.replaceChildren(...data.sheets.map((item) => Object.assign(document.createElement("option"), { value: item.name, textContent: item.name }))); select.disabled = false; $("#previewGoogleSheetBtn").disabled = !data.sheets.length; $("#googlePreviewHint").textContent = `已读取 ${data.sheets.length} 个工作表；下一步点击“2. 读取表头与预览”`; googleRecords = []; googleHeaders = []; $("#googleRoleFilter").hidden = true; $("#googlePreview").hidden = true; setGoogleStatus("googleSheetStatus", "Google 服务账号已就绪 · 工作表已读取", "ready"); googleActivity(`成功读取 ${data.sheets.length} 个工作表。请选择目标 Sheet。`, "OK"); log(`已读取 Google 表格 ${data.spreadsheetId} 的 ${data.sheets.length} 个工作表。`, "OK"); } catch (error) { setGoogleStatus("googleSheetStatus", error.message, "error"); googleActivity(`读取工作表失败：${error.message}`, "ERROR"); } finally { button.disabled = false; button.textContent = "1. 获取工作表"; } }
function googleImportSettings() { return state.googleImport ||= { roleColumn: "", textColumn: "", keyColumn: "", characterNames: "" }; }
function normalizedCharacterName(value) { return String(value || "").trim().toLocaleLowerCase(); }
function requestedCharacterNames() { return [...new Set(googleImportSettings().characterNames.split(/[，,\n\r]+/).map(normalizedCharacterName).filter(Boolean))]; }
function googleTextsForImport() { const settings = googleImportSettings(); const names = requestedCharacterNames(); const keyFor = (record) => String(record[settings.keyColumn] || "").trim(); if (!settings.textColumn) return { valid: false, filtered: !!names.length, message: "请选择需要配音的文本列", items: [], texts: [] }; if (!names.length) { const items = googleRecords.map((record) => ({ text: String(record[settings.textColumn] || "").trim(), sourceKey: keyFor(record) })).filter((item) => item.text); return { valid: true, filtered: false, items, texts: items.map((item) => item.text) }; } if (!settings.roleColumn) return { valid: false, filtered: true, message: "填写角色名后，请同时选择角色名列", items: [], texts: [] }; const wanted = new Set(names); const records = googleRecords.filter((record) => wanted.has(normalizedCharacterName(record[settings.roleColumn]))); const items = records.map((record) => ({ text: String(record[settings.textColumn] || "").trim(), sourceKey: keyFor(record) })).filter((item) => item.text); return { valid: true, filtered: true, records, names, items, texts: items.map((item) => item.text) }; }
function updateGoogleRolePreview() { const result = googleTextsForImport(); const preview = $("#googlePreview"); const hint = $("#googleRoleFilterHint"); if (!result.valid) { preview.textContent = result.message; hint.textContent = result.message; $("#importGoogleSheetTextBtn").disabled = true; return; } const settings = googleImportSettings(); if (!result.filtered) { const lines = result.items.slice(0, 12).map((item) => item.text); preview.textContent = lines.length ? `${lines.join("\n")}\n\n将从「${settings.textColumn}」导入 ${result.texts.length} 条文本。` : `「${settings.textColumn}」没有可导入的文本。`; hint.textContent = "未填写角色名：将导入配音文本列中的全部非空文本。"; $("#importGoogleSheetTextBtn").disabled = !result.texts.length; return; } const lines = result.records.slice(0, 12).map((record) => `${record[settings.roleColumn] || ""}  →  ${record[settings.textColumn] || ""}`).filter(Boolean); preview.textContent = lines.length ? `${lines.join("\n")}\n\n已匹配 ${result.records.length} 行，待导入 ${result.texts.length} 条 ${settings.textColumn} 文本。` : "没有找到匹配的角色名。"; hint.textContent = `已填写 ${result.names.length} 个角色名，精确匹配角色名列后只导入 ${settings.textColumn}。`; $("#importGoogleSheetTextBtn").disabled = !result.texts.length; }
function syncGoogleRoleImport() { const settings = googleImportSettings(); settings.roleColumn = $("#googleRoleColumn").value; settings.textColumn = $("#googleTextColumn").value; settings.keyColumn = $("#googleKeyColumn").value; settings.characterNames = $("#googleRoleNames").value; saveProject(false); updateGoogleRolePreview(); }
function renderGooglePreview() { const settings = googleImportSettings(); const roleCandidate = googleHeaders.find((header) => /角色|role|character|name/i.test(header)) || ""; const textCandidate = googleHeaders.find((header) => /日语|日文|japanese|英文|english|中文|chinese|台词|文本|text|dialogue/i.test(header)) || ""; const keyCandidate = googleHeaders.find((header) => /^key$/i.test(header) || /(^|[_\s])key($|[_\s])/i.test(header) || /^dialog$/i.test(header)) || googleHeaders[0] || ""; if (!googleHeaders.includes(settings.roleColumn)) settings.roleColumn = roleCandidate; if (!googleHeaders.includes(settings.textColumn)) settings.textColumn = textCandidate; if (!googleHeaders.includes(settings.keyColumn)) settings.keyColumn = keyCandidate; [["#googleTextColumn", "请选择需要配音的文本列", settings.textColumn], ["#googleRoleColumn", "不按角色筛选", settings.roleColumn], ["#googleKeyColumn", "不使用 Key 命名", settings.keyColumn]].forEach(([selector, placeholder, value]) => { const select = $(selector); select.replaceChildren(Object.assign(document.createElement("option"), { value: "", textContent: placeholder }), ...googleHeaders.map((header) => Object.assign(document.createElement("option"), { value: header, textContent: header }))); select.value = value; }); $("#googleRoleNames").value = settings.characterNames; $("#googleRoleFilter").hidden = !googleHeaders.length; $("#googlePreview").hidden = false; updateGoogleRolePreview(); }
async function previewGoogleSheet() { if (!$("#googleSheetTab").value) { setGoogleStatus("googleSheetStatus", "请先获取并选择工作表", "error"); googleActivity("读取表头失败：尚未选择工作表。", "ERROR"); return; } const { headerRow, startRow, endRow } = googleImportBody(); if (!headerRow || !startRow || !endRow || endRow < startRow) { setGoogleStatus("googleSheetStatus", "请检查表头行与起止行", "error"); googleActivity("读取表头失败：行范围无效。", "ERROR"); return; } const button = $("#previewGoogleSheetBtn"); button.disabled = true; button.textContent = "正在读取…"; googleActivity(`正在读取 ${$("#googleSheetTab").value} 的第 ${headerRow} 至 ${endRow} 行…`); try { const data = await localAssistant("/google/read", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(googleImportBody()) }); googleHeaders = data.headers || []; googleRecords = data.records || []; renderGooglePreview(); $("#googlePreviewHint").textContent = `已读取 ${googleRecords.length} 行、${googleHeaders.length} 列；请在下方选择配音文本列`; setGoogleStatus("googleSheetStatus", "Google 表格已读取，请选择配音文本列", "ready"); googleActivity(`已读取 ${googleRecords.length} 行、${googleHeaders.length} 列。请指定“配音文本列”。`, "OK"); log(`已从 Google 表格读取 ${googleRecords.length} 行文本预览。`, "OK"); } catch (error) { setGoogleStatus("googleSheetStatus", error.message, "error"); googleActivity(`读取表头和内容失败：${error.message}`, "ERROR"); } finally { button.disabled = false; button.textContent = "2. 读取表头与预览"; } }
function importGoogleSheetText() { const result = googleTextsForImport(); if (!result.valid) return toast(result.message, true); if (!result.items.length) return toast(result.filtered ? "没有匹配角色的可导入文本" : "配音文本列没有可导入的文本", true); const rows = result.items.map((item, index) => ({ id: `${Date.now()}-${index}`, text: item.text, sourceKey: item.sourceKey, status: "待生成" })); replaceImportedRows(rows, "Google 表格"); closeGoogleSheetDialog(); toast(`已导入 ${rows.length} 条 Google 表格文本，并清空此前文本`); log(result.filtered ? `已按角色筛选导入 ${rows.length} 条 ${googleImportSettings().textColumn} 文本。` : `已从 Google 表格的 ${googleImportSettings().textColumn} 列导入 ${rows.length} 条文本。`, "OK"); }
function closeGoogleWriteDialog() { $("#googleWriteDialog").hidden = true; }
async function openGoogleWriteDialog() { $("#googleWriteDialog").hidden = false; $("#googleWriteSummary").textContent = `将写入当前 ${state.rows.length} 条配音文本。目标单元格及其向下区域内的现有内容会被覆盖。`; $("#confirmGoogleWriteBtn").disabled = true; await checkGoogleAssistant("googleWriteStatus"); }
async function loadGoogleWriteSheets() { const spreadsheet = $("#googleWriteUrl").value.trim(); if (!spreadsheet) return toast("请先粘贴 Google 表格链接或 Spreadsheet ID", true); const button = $("#loadGoogleWriteSheetsBtn"); button.disabled = true; button.textContent = "正在读取…"; try { const data = await localAssistant("/google/sheets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ spreadsheet }) }); googleWriteSpreadsheetId = data.spreadsheetId; const select = $("#googleWriteSheet"); select.replaceChildren(...data.sheets.map((item) => Object.assign(document.createElement("option"), { value: item.name, textContent: item.name }))); select.disabled = false; $("#confirmGoogleWriteBtn").disabled = !data.sheets.length; log(`已读取 Google 写入目标 ${data.spreadsheetId} 的工作表。`, "OK"); } catch (error) { toast(error.message, true); log(`读取 Google 写入目标失败：${error.message}`, "ERROR"); } finally { button.disabled = false; button.textContent = "读取工作表"; } }
async function writeGoogleSheet() { const sheet = $("#googleWriteSheet").value; const startCell = $("#googleWriteCell").value.trim().toUpperCase(); if (!googleWriteSpreadsheetId || !sheet) return toast("请先读取并选择写入工作表", true); if (!/^[A-Z]{1,3}[1-9]\d*$/.test(startCell)) return toast("起始单元格格式应如 A1", true); const values = [$("#googleWriteHeader").checked ? ["文本"] : [], ...state.rows.map((row) => [row.text || ""])].filter((row) => row.length); if (!values.length) return toast("没有可写入的文本", true); if (!window.confirm(`确认写入 ${values.length} 行到 Google 表格「${sheet}」的 ${startCell} 起始位置吗？\n目标区域内现有内容将被覆盖。`)) return; const button = $("#confirmGoogleWriteBtn"); button.disabled = true; button.textContent = "正在写入…"; try { const data = await localAssistant("/google/write", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ spreadsheet: googleWriteSpreadsheetId, sheet, startCell, values }) }); closeGoogleWriteDialog(); toast(`已写入 ${data.updatedCells || values.length} 个单元格`); log(`已写入 Google 表格：${data.updatedRange || `${sheet}!${startCell}`}。`, "OK"); } catch (error) { toast(error.message, true); log(`写入 Google 表格失败：${error.message}`, "ERROR"); } finally { button.disabled = false; button.textContent = "确认写入"; } }
function showLogin(message = "") { $("#loginLayer").hidden = false; $("#loginMessage").textContent = message; $("#loginMessage").classList.remove("is-ok"); $("#loginPassword").value = ""; $("#loginUsername").focus(); }
function setLoginUi() { const loggedIn = !!savedAuth(); $("#loginLayer").hidden = loggedIn; $("#loginBtn").textContent = loggedIn ? `${sessionStorage.getItem(AUTH_NAME_STORAGE) || "已登录"} · 退出` : "登录使用"; }
function logout(message = "") { sessionStorage.removeItem(AUTH_STORAGE); sessionStorage.removeItem(AUTH_NAME_STORAGE); setLoginUi(); if (message) $("#loginMessage").textContent = message; }
async function login(username, password) { const message = $("#loginMessage"); message.textContent = "正在验证登录信息…"; message.classList.remove("is-ok"); const response = await fetch(`${apiBase()}/api/session`, { headers: { "X-Voice-Studio-Auth": authToken(username, password) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "登录失败"); sessionStorage.setItem(AUTH_STORAGE, authToken(username, password)); sessionStorage.setItem(AUTH_NAME_STORAGE, body.username || username); message.textContent = "登录成功"; message.classList.add("is-ok"); setLoginUi(); log(`账户 ${body.username || username} 已登录。`, "OK"); loadVoices().catch((error) => { log(`音色列表加载失败：${error.message}`, "ERROR"); $("#voiceCatalogHint").textContent = "音色列表加载失败，可点击刷新重试"; }); }
function hexBlob(hex, format) { const source = String(hex || "").trim().replace(/^0x/i, ""); if (!source || source.length % 2 || !/^[\da-f]+$/i.test(source)) throw new Error("接口返回的音频数据不完整"); const bytes = new Uint8Array(source.length / 2); for (let index = 0; index < bytes.length; index += 1) bytes[index] = parseInt(source.slice(index * 2, index * 2 + 2), 16); const mime = { mp3: "audio/mpeg", wav: "audio/wav", flac: "audio/flac", opus: "audio/ogg" }[format] || `audio/${format}`; return new Blob([bytes], { type: mime }); }
function base64FromBuffer(buffer) { const bytes = new Uint8Array(buffer); let binary = ""; for (let offset = 0; offset < bytes.length; offset += 0x8000) binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000)); return btoa(binary); }
async function saveAudioToOutputFolder(blob, row, index) { const audioBase64 = base64FromBuffer(await blob.arrayBuffer()); const result = await localAssistant("/audio/save", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ filename: audioFileName(row, index), audioBase64 }) }); row.outputPath = result.path; return result; }
async function openOutputFolder() { try { const result = await localAssistant("/audio/open-folder", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); toast("已打开配音输出文件夹"); log(`已打开输出文件夹：${result.folder}`, "OK"); } catch (error) { toast("输出文件夹仅能在桌面应用中打开", true); log(`打开输出文件夹失败：${error.message}`, "ERROR"); } }
async function generate(index) { const row = state.rows[index]; if (!row?.text?.trim()) throw new Error("文本不能为空"); if (!apiBase()) throw new Error("请先填写语音接口地址"); if (!savedAuth()) { showLogin("请先登录后再生成语音"); throw new Error("请先登录"); } row.status = "生成中"; render(); const p = params(row); log(`第 ${index + 1} 条开始生成：模型 ${state.settings.model}，音色 ${p.voice}。`); const response = await fetch(`${apiBase()}/api/tts`, { method: "POST", headers: { "Content-Type": "application/json", "X-Voice-Studio-Auth": savedAuth() }, body: JSON.stringify({ model: state.settings.model, text: row.text.trim(), stream: false, voice_setting: { voice_id: p.voice, speed: p.speed, vol: p.volume, pitch: p.pitch }, audio_setting: { sample_rate: 32000, bitrate: 128000, format: state.settings.format, channel: 1 }, output_format: "hex", subtitle_enable: false }) }); const body = await response.json().catch(() => ({})); if (response.status === 401) { logout("登录已失效，请重新登录"); throw new Error("登录已失效"); } if (!response.ok || body.base_resp?.status_code) throw new Error(body.base_resp?.status_msg || body.error || "MiniMax 请求失败"); if (!body.data?.audio) throw new Error("接口未返回音频数据"); const audioBlob = hexBlob(body.data.audio, state.settings.format); if (row.audioUrl) URL.revokeObjectURL(row.audioUrl); row.audioUrl = URL.createObjectURL(audioBlob); row.duration = Math.round((body.extra_info?.audio_length || duration(row) * 1000) / 1000); try { const saved = await saveAudioToOutputFolder(audioBlob, row, index); log(`第 ${index + 1} 条已保存到输出文件夹：${saved.filename}。`, "OK"); } catch (error) { log(`第 ${index + 1} 条仅保留在页面中，未写入输出文件夹：${error.message}`, "INFO"); } row.status = "已生成"; render(); log(`第 ${index + 1} 条生成成功：${time(row.duration)}，追踪 ID ${body.trace_id || "未提供"}。`, "OK"); return row; }
async function playRow(index) { const row = state.rows[index]; if (!row?.audioUrl) return; state.selected = index; render(); e.audio.pause(); e.audio.currentTime = 0; try { await e.audio.play(); log(`正在播放第 ${index + 1} 条完整音频。`, "OK"); } catch { log(`第 ${index + 1} 条已生成，请使用音频播放器开始播放。`, "INFO"); toast("音频已生成，请使用右侧播放器开始播放"); } }
async function generateMany(indices, autoPlay = false) { const list = [...new Set(indices)].filter((index) => state.rows[index]); if (!list.length) return toast("请先选择一条文本", true); log(`开始处理 ${list.length} 条配音任务。`); let count = 0; for (const index of list) { try { await generate(index); count += 1; if (autoPlay && count === 1) await playRow(index); } catch (error) { state.rows[index].status = "失败"; render(); log(`第 ${index + 1} 条生成失败：${error.message}`, "ERROR"); toast(`第 ${index + 1} 条失败：${error.message}`, true); } } if (count) { log(`任务完成：成功 ${count}/${list.length} 条。`, "OK"); toast(autoPlay ? "已生成并开始播放完整音频" : `已生成 ${count} 条音频`); } }
function audioFileName(row, index) { const key = String(row.sourceKey || "").trim(); const code = String(state.settings.filenameCode || "").trim(); const match = key.match(/^[^_]+_(\d+)_(\d+)$/); if (match && code) return `C${code}_${match[1].padStart(2, "0")}_${match[2].padStart(3, "0")}.${state.settings.format}`; return `voice-${String(index + 1).padStart(2, "0")}.${state.settings.format}`; }
function cvFileName(row, index) { return audioFileName(row, index).replace(/\.[^.]+$/, ""); }
async function writeLevelDialogCv(entries) { const items = entries.map(({ row, index }) => ({ sourceKey: String(row.sourceKey || "").trim(), cvName: cvFileName(row, index) })).filter((item) => item.sourceKey); if (!items.length) return { updated: [], missing: [] }; const result = await localAssistant("/google/write-level-dialog-cv", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items }) }); if (result.updated?.length) log(`已回填 LevelDialogConfig 的 M 列 CV：${result.updated.length} 条。`, "OK"); if (result.missing?.length) log(`未在 LevelDialogConfig 的 G 列 dialog 找到 ${result.missing.length} 个 Key：${result.missing.join("、")}`, "ERROR"); return result; }
async function generateManyWithCv(indices, autoPlay = false) { const list = [...new Set(indices)].filter((index) => state.rows[index]); if (!list.length) return toast("请先选择一条文本", true); log(`开始处理 ${list.length} 条配音任务。`); let count = 0; const completed = []; for (const index of list) { try { await generate(index); completed.push({ row: state.rows[index], index }); count += 1; if (autoPlay && count === 1) await playRow(index); } catch (error) { state.rows[index].status = "失败"; render(); log(`第 ${index + 1} 条生成失败：${error.message}`, "ERROR"); toast(`第 ${index + 1} 条失败：${error.message}`, true); } } if (completed.some(({ row }) => row.sourceKey)) { try { await writeLevelDialogCv(completed); } catch (error) { log(`音频已生成，但 LevelDialogConfig 的 CV 回填失败：${error.message}`, "ERROR"); toast("音频已生成，但 CV 回填失败；请查看日志", true); } } if (count) { log(`任务完成：成功 ${count}/${list.length} 条。`, "OK"); toast(autoPlay ? "已生成、播放并回填 CV" : `已生成 ${count} 条音频并回填 CV`); } }
window.addEventListener("load", () => { $("#testRowBtn").onclick = () => generateManyWithCv([state.selected], true); $("#generateAllBtn").onclick = () => generateManyWithCv(state.rows.map((_, index) => index)); });
const REQUEST_GAP_MS = 750;
const RATE_LIMIT_WAIT_MS = 60_000;
const MAX_RATE_LIMIT_RETRIES = 3;
const wait = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
function isRateLimitError(error) { return /rate\s*limit|rpm|too many requests|\b429\b/i.test(String(error?.message || error)); }
async function generateWithRateLimitRetry(index) { for (let attempt = 0; attempt <= MAX_RATE_LIMIT_RETRIES; attempt += 1) { try { return await generate(index); } catch (error) { if (!isRateLimitError(error) || attempt === MAX_RATE_LIMIT_RETRIES) throw error; const retry = attempt + 1; state.rows[index].status = "限流等待"; render(); log(`第 ${index + 1} 条触发 RPM 限制，等待 60 秒后自动重试（${retry}/${MAX_RATE_LIMIT_RETRIES}）。`, "INFO"); toast(`触发接口频率限制，正在等待后自动重试（${retry}/${MAX_RATE_LIMIT_RETRIES}）`); await wait(RATE_LIMIT_WAIT_MS); } } }
async function generateManyWithRateLimit(indices, autoPlay = false) { const list = [...new Set(indices)].filter((index) => state.rows[index] && state.rows[index].status !== "已生成"); if (!list.length) return toast("没有待生成的文本"); log(`开始处理 ${list.length} 条待生成任务；每条间隔 ${REQUEST_GAP_MS / 1000} 秒。`); let count = 0; const completed = []; for (const [position, index] of list.entries()) { if (position) await wait(REQUEST_GAP_MS); try { await generateWithRateLimitRetry(index); completed.push({ row: state.rows[index], index }); count += 1; if (autoPlay && count === 1) await playRow(index); } catch (error) { state.rows[index].status = "失败"; render(); log(`第 ${index + 1} 条生成失败：${error.message}`, "ERROR"); toast(`第 ${index + 1} 条失败：${error.message}`, true); } } if (completed.some(({ row }) => row.sourceKey)) { try { await writeLevelDialogCv(completed); } catch (error) { log(`音频已生成，但 LevelDialogConfig 的 CV 回填失败：${error.message}`, "ERROR"); toast("音频已生成，但 CV 回填失败；请查看日志", true); } } if (count) { log(`任务完成：成功 ${count}/${list.length} 条。`, "OK"); toast(autoPlay ? "已生成、播放并回填 CV" : `已生成 ${count} 条音频并回填 CV`); } }
window.addEventListener("load", () => { $("#testRowBtn").onclick = () => generateManyWithRateLimit([state.selected], true); $("#generateAllBtn").onclick = () => generateManyWithRateLimit(state.rows.map((_, index) => index)); });
let batchRunActive = false;
let batchStopRequested = false;
function setBatchRunUi(active) { const button = $("#stopGenerationBtn"); button.hidden = !active; button.disabled = false; button.textContent = "中止生成"; $("#generateAllBtn").disabled = active; $("#regenerateAllBtn").disabled = active; }
function stopBatchGeneration() { if (!batchRunActive) return; batchStopRequested = true; const button = $("#stopGenerationBtn"); button.disabled = true; button.textContent = "正在中止…"; log("已请求中止：当前请求完成后将暂停，未完成条目会保留供下次继续。", "INFO"); toast("正在中止，当前条完成后会暂停"); }
async function waitWhileBatchActive(milliseconds) { const deadline = Date.now() + milliseconds; while (!batchStopRequested && Date.now() < deadline) await wait(Math.min(250, deadline - Date.now())); return !batchStopRequested; }
async function generateWithPauseAndRetry(index) { for (let attempt = 0; attempt <= MAX_RATE_LIMIT_RETRIES; attempt += 1) { if (batchStopRequested) return null; try { return await generate(index); } catch (error) { if (!isRateLimitError(error) || attempt === MAX_RATE_LIMIT_RETRIES) throw error; const retry = attempt + 1; state.rows[index].status = "限流等待"; render(); log(`第 ${index + 1} 条触发 RPM 限制，等待 60 秒后自动重试（${retry}/${MAX_RATE_LIMIT_RETRIES}）。`, "INFO"); toast(`触发接口频率限制，正在等待后自动重试（${retry}/${MAX_RATE_LIMIT_RETRIES}）`); if (!(await waitWhileBatchActive(RATE_LIMIT_WAIT_MS))) return null; } } }
async function generateManyControlled(indices, autoPlay = false, regenerateAll = false) { if (batchRunActive) return toast("当前批量任务仍在运行"); const list = [...new Set(indices)].filter((index) => state.rows[index] && (regenerateAll || state.rows[index].status !== "已生成")); if (!list.length) return toast("没有待生成的文本"); batchRunActive = true; batchStopRequested = false; setBatchRunUi(true); log(`${regenerateAll ? "开始重新生成" : "开始处理"} ${list.length} 条任务；每条间隔 ${REQUEST_GAP_MS / 1000} 秒。`); let count = 0; let stopped = false; const completed = []; try { for (const [position, index] of list.entries()) { if (batchStopRequested || (position && !(await waitWhileBatchActive(REQUEST_GAP_MS)))) { stopped = true; break; } const row = await generateWithPauseAndRetry(index); if (!row) { stopped = true; break; } completed.push({ row, index }); count += 1; if (autoPlay && count === 1) await playRow(index); } if (completed.some(({ row }) => row.sourceKey)) { try { await writeLevelDialogCv(completed); } catch (error) { log(`音频已生成，但 LevelDialogConfig 的 CV 回填失败：${error.message}`, "ERROR"); toast("音频已生成，但 CV 回填失败；请查看日志", true); } } } catch (error) { log(`批量任务异常中止：${error.message}`, "ERROR"); toast(`批量任务中止：${error.message}`, true); } finally { batchRunActive = false; setBatchRunUi(false); } const next = state.rows.findIndex((row) => row.status !== "已生成"); if (stopped || batchStopRequested) { const hint = regenerateAll ? "下次可再次点击“重新全部生成”继续覆盖。" : next >= 0 ? `下次会从第 ${next + 1} 条继续。` : "所有文本均已完成。"; log(`批量任务已暂停，当前完成 ${count} 条；${hint}`, "INFO"); toast(`已中止。${hint}`); } else if (count) { log(`任务完成：成功 ${count}/${list.length} 条。`, "OK"); toast(regenerateAll ? `已重新生成并覆盖 ${count} 条音频` : autoPlay ? "已生成、播放并回填 CV" : `已生成 ${count} 条音频并回填 CV`); } }
window.addEventListener("load", () => { $("#testRowBtn").onclick = () => generateManyControlled([state.selected], true); $("#generateAllBtn").onclick = () => generateManyControlled(state.rows.map((_, index) => index)); $("#regenerateAllBtn").onclick = () => generateManyControlled(state.rows.map((_, index) => index), false, true); $("#stopGenerationBtn").onclick = stopBatchGeneration; });
function download(index) { const row = state.rows[index]; if (!row?.audioUrl) return; const link = document.createElement("a"); link.href = row.audioUrl; link.download = audioFileName(row, index); link.click(); log(`已下载第 ${index + 1} 条音频：${link.download}。`, "OK"); }
function importFile(file) { const reader = new FileReader(); reader.onload = () => { try { const wb = XLSX.read(reader.result, { type: "array" }); const data = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1, defval: "" }); const start = data[0]?.some((v) => /文本|text/i.test(String(v))) ? 1 : 0; const rows = data.slice(start).map((line) => String(line[0] || "").trim()).filter(Boolean); if (!rows.length) throw new Error("未找到第一列文本"); replaceImportedRows(rows.map((text, i) => ({ id: `${Date.now()}-${i}`, text, status: "待生成" })), file.name); toast(`已导入 ${rows.length} 条文本，并清空此前文本`); } catch (error) { log(`导入失败：${error.message}`, "ERROR"); toast(`导入失败：${error.message}`, true); } }; reader.readAsArrayBuffer(file); }
function exportExcel() { const data = [["文本", "文件 Key", "输出文件名", "音色 ID", "语速", "音调", "音量", "状态"]].concat(state.rows.map((row, index) => { const p = params(row); return [row.text, row.sourceKey || "", audioFileName(row, index), p.voice, p.speed, p.pitch, p.volume, row.status]; })); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(data), "配音文本"); XLSX.writeFile(wb, "voice-studio.xlsx"); }
function exportProject() { const body = JSON.stringify({ ...state, rows: state.rows.map(({ audioUrl, ...row }) => row) }, null, 2); const url = URL.createObjectURL(new Blob([body], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "voice-studio-project.json"; link.click(); URL.revokeObjectURL(url); }
function bind() {
  $("#loginForm").onsubmit = async (event) => { event.preventDefault(); try { await login($("#loginUsername").value.trim(), $("#loginPassword").value); } catch (error) { $("#loginMessage").textContent = error.message; $("#loginMessage").classList.remove("is-ok"); } };
  $("#loginBtn").onclick = () => savedAuth() ? logout() : showLogin();
  $("#saveProjectBtn").onclick = () => saveProject(true);
  $("#importDingTalkBtn").onclick = () => openDingTalkDialog(); $("#closeDingTalkDialogBtn").onclick = closeDingTalkDialog; $("#cancelDingTalkDialogBtn").onclick = closeDingTalkDialog; $("#loadDingTalkSheetsBtn").onclick = loadDingTalkSheets; $("#previewDingTalkBtn").onclick = previewDingTalk; $("#importDingTalkTextBtn").onclick = importDingTalkText;
  $("#importGoogleSheetBtn").onclick = () => openGoogleSheetDialog(); $("#closeGoogleSheetDialogBtn").onclick = closeGoogleSheetDialog; $("#cancelGoogleSheetDialogBtn").onclick = closeGoogleSheetDialog; $("#loadGoogleSheetsBtn").onclick = loadGoogleImportSheets; $("#previewGoogleSheetBtn").onclick = previewGoogleSheet; $("#importGoogleSheetTextBtn").onclick = importGoogleSheetText; $("#googleRoleColumn").onchange = syncGoogleRoleImport; $("#googleTextColumn").onchange = syncGoogleRoleImport; $("#googleKeyColumn").onchange = syncGoogleRoleImport; $("#googleRoleNames").oninput = syncGoogleRoleImport; $("#writeGoogleSheetBtn").onclick = () => openGoogleWriteDialog(); $("#closeGoogleWriteDialogBtn").onclick = closeGoogleWriteDialog; $("#cancelGoogleWriteDialogBtn").onclick = closeGoogleWriteDialog; $("#loadGoogleWriteSheetsBtn").onclick = loadGoogleWriteSheets; $("#confirmGoogleWriteBtn").onclick = writeGoogleSheet;
  $("#manageVoicesBtn").onclick = () => openVoiceDialog().catch((error) => toast(error.message, true)); $("#closeVoiceDialogBtn").onclick = closeVoiceDialog; $("#cancelVoiceDialogBtn").onclick = closeVoiceDialog; $("#saveVoiceFilterBtn").onclick = saveVoiceFilter; $("#voiceSearch").oninput = renderVoiceDialog; $("#selectAllVoicesBtn").onclick = () => { voiceDialogSelection = new Set(voiceCatalog.map((voice) => voice.id)); renderVoiceDialog(); }; $("#clearVoiceSelectionBtn").onclick = () => { voiceDialogSelection.clear(); renderVoiceDialog(); }; $("#voicePickerList").onchange = (event) => { if (!event.target.matches('input[type="checkbox"]')) return; event.target.checked ? voiceDialogSelection.add(event.target.value) : voiceDialogSelection.delete(event.target.value); $("#voiceSelectionSummary").textContent = `已选 ${voiceDialogSelection.size} / ${voiceCatalog.length} 个音色`; };
  $("#addTextBtn").onclick = () => add(); $("#addRowBtn").onclick = () => add(); $("#excelInput").onchange = (event) => event.target.files[0] && importFile(event.target.files[0]); $("#openOutputFolderBtn").onclick = openOutputFolder; $("#exportExcelBtn").onclick = () => { exportExcel(); log("已导出 Excel 文本表。", "OK"); }; $("#exportProjectBtn").onclick = () => { exportProject(); log("已导出项目配置。", "OK"); }; $("#testRowBtn").onclick = () => generateMany([state.selected], true); $("#generateAllBtn").onclick = () => generateMany(state.rows.map((_, i) => i)); $("#refreshVoicesBtn").onclick = () => loadVoices().catch((error) => { log(`音色列表加载失败：${error.message}`, "ERROR"); toast(error.message, true); }); $("#clearSelectionBtn").onclick = () => { state.selectedIds = []; render(); log("已取消所有文本选择。"); }; $("#deleteRowBtn").onclick = () => { if (state.rows.length < 2) return toast("至少保留一条文本", true); state.rows.splice(state.selected, 1); state.selected = Math.max(0, state.selected - 1); state.selectedIds = [state.selected]; render(); log("已删除当前文本。"); }; $("#clearAudioBtn").onclick = () => { state.rows.forEach((r) => { if (r.audioUrl) URL.revokeObjectURL(r.audioUrl); delete r.audioUrl; delete r.duration; r.status = "待生成"; }); render(); log("已清除全部音频结果。"); toast("已清除音频结果"); }; $("#apiHelpBtn").onclick = () => toast("MiniMax Key 只保存在接口服务器的 MINIMAX_API_KEY 环境变量中。") ; $("#resetProjectBtn").onclick = () => { localStorage.removeItem(STORAGE); localStorage.removeItem(SAVED_AT_STORAGE); location.reload(); }; $("#clearLogBtn").onclick = () => { logs.length = 0; $("#logOutput").textContent = "日志已清空。"; }; $("#toggleLogBtn").onclick = () => { const panel = $("#logPanel"); const collapsed = panel.classList.toggle("is-collapsed"); $("#toggleLogBtn").setAttribute("aria-expanded", String(!collapsed)); $("#logToggleText").textContent = collapsed ? "展开日志" : "收起日志"; };
  e.body.onchange = (event) => { if (!event.target.matches(".row-check")) return; const index = +event.target.dataset.index; state.selectedIds = event.target.checked ? [...new Set([...state.selectedIds, index])] : state.selectedIds.filter((i) => i !== index); state.selected = index; render(); }; e.body.onclick = (event) => { const button = event.target.closest("button[data-index]"); if (!button) return; const index = +button.dataset.index; button.dataset.download === "yes" ? download(index) : select(index); }; $("#selectAll").onchange = (event) => { state.selectedIds = event.target.checked ? state.rows.map((_, i) => i) : []; render(); };
  e.text.oninput = () => { current().text = e.text.value; render(); }; e.override.onchange = () => { const row = current(); row.override = e.override.checked; if (row.override) Object.assign(row, params(row)); render(); }; [["rowVoice", "voice"], ["rowSpeed", "speed"], ["rowPitch", "pitch"], ["rowVolume", "volume"]].forEach(([id, kind]) => { const handler = (event) => { const row = current(); row.override = true; row[kind] = kind === "voice" ? event.target.value.trim() : +event.target.value; if (kind !== "voice") valueLabel(event.target, kind); render(); }; $(`#${id}`).oninput = handler; $(`#${id}`).onchange = handler; }); $("#resetRowBtn").onclick = () => { current().override = false; render(); };
  [["apiBaseUrl", "apiBase"], ["globalModel", "model"], ["globalVoice", "voice"], ["filenameCode", "filenameCode"], ["globalSpeed", "speed"], ["globalPitch", "pitch"], ["globalVolume", "volume"]].forEach(([id, kind]) => { const handler = (event) => { state.settings[kind] = ["apiBase", "model", "voice", "filenameCode"].includes(kind) ? event.target.value.trim() : +event.target.value; if (!["apiBase", "model", "voice", "filenameCode"].includes(kind)) valueLabel(event.target, kind); render(); }; $(`#${id}`).oninput = handler; $(`#${id}`).onchange = handler; }); document.querySelectorAll(".format-chip").forEach((button) => button.onclick = () => { state.settings.format = button.dataset.format; render(); });
}
bind(); render(!restoredProject); updateSaveHint(restoredProject); window.addEventListener("beforeunload", () => saveProject(false)); setLoginUi(); if (savedAuth()) loadVoices().catch((error) => { log(`音色列表加载失败：${error.message}`, "ERROR"); $("#voiceCatalogHint").textContent = "音色列表加载失败，可点击刷新重试"; }); log(restoredProject ? "已恢复上次保存的项目。" : "工作台已就绪，等待登录和配音任务。");
